// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD442gOBx3Sjg4bQvt49d29P_nRMhePuPw',
    appId: '1:981862721318:web:20d4d9a284356041f543e7',
    messagingSenderId: '981862721318',
    projectId: 'port-casablanca',
    authDomain: 'port-casablanca.firebaseapp.com',
    storageBucket: 'port-casablanca.firebasestorage.app',
    measurementId: 'G-WJSSV7DMY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5eSm8dqFsJ0jBT0Mql8J7ixqv2U5xpwg',
    appId: '1:981862721318:android:9933c9dbe9fa1460f543e7',
    messagingSenderId: '981862721318',
    projectId: 'port-casablanca',
    storageBucket: 'port-casablanca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWvgmwtALdL85kiouuVCJDcIl0t5CTDos',
    appId: '1:981862721318:ios:1dcaa7b704134990f543e7',
    messagingSenderId: '981862721318',
    projectId: 'port-casablanca',
    storageBucket: 'port-casablanca.firebasestorage.app',
    iosBundleId: 'com.example.portCasa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWvgmwtALdL85kiouuVCJDcIl0t5CTDos',
    appId: '1:981862721318:ios:1dcaa7b704134990f543e7',
    messagingSenderId: '981862721318',
    projectId: 'port-casablanca',
    storageBucket: 'port-casablanca.firebasestorage.app',
    iosBundleId: 'com.example.portCasa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD442gOBx3Sjg4bQvt49d29P_nRMhePuPw',
    appId: '1:981862721318:web:025f116d76a92588f543e7',
    messagingSenderId: '981862721318',
    projectId: 'port-casablanca',
    authDomain: 'port-casablanca.firebaseapp.com',
    storageBucket: 'port-casablanca.firebasestorage.app',
    measurementId: 'G-Z5GZ277XL4',
  );
}
