// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYuayK6BvTRHzZEeZ8ISmOJKcfQQ9za0I',
    appId: '1:832242923912:web:325a954c9e2861fb3a223d',
    messagingSenderId: '832242923912',
    projectId: 'port-casa',
    authDomain: 'port-casa.firebaseapp.com',
    storageBucket: 'port-casa.firebasestorage.app',
    measurementId: 'G-W2PZ2K62EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkgW_-7MugpdqF7i9R5wpnS9T14v_Uw-E',
    appId: '1:832242923912:android:4927b87d5dd935123a223d',
    messagingSenderId: '832242923912',
    projectId: 'port-casa',
    storageBucket: 'port-casa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3gv3UJ2h2WhHhch8r5shUk5iWzPzz-64',
    appId: '1:832242923912:ios:e487294a48e101a83a223d',
    messagingSenderId: '832242923912',
    projectId: 'port-casa',
    storageBucket: 'port-casa.firebasestorage.app',
    iosBundleId: 'com.example.portCasa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3gv3UJ2h2WhHhch8r5shUk5iWzPzz-64',
    appId: '1:832242923912:ios:e487294a48e101a83a223d',
    messagingSenderId: '832242923912',
    projectId: 'port-casa',
    storageBucket: 'port-casa.firebasestorage.app',
    iosBundleId: 'com.example.portCasa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYuayK6BvTRHzZEeZ8ISmOJKcfQQ9za0I',
    appId: '1:832242923912:web:623687af2ab0b1513a223d',
    messagingSenderId: '832242923912',
    projectId: 'port-casa',
    authDomain: 'port-casa.firebaseapp.com',
    storageBucket: 'port-casa.firebasestorage.app',
    measurementId: 'G-1XCBX4T6K2',
  );
}
